# Generated by Django 5.1.7 on 2025-03-17 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
