# Generated by Django 5.1.7 on 2025-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_options_alter_song_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
