# Generated by Django 5.1.7 on 2025-03-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_audio_file_song_audio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio_url',
            new_name='youtube_url',
        ),
    ]
