# Generated by Django 5.1.7 on 2025-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_audio_url_song_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
