# Generated by Django 5.1.7 on 2025-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
